# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Rohith Nagabhyrava
title: Ms in Data Analytics, Northeastern University
email: nagabhyrava.r@husky.neu.edu
website: rnagabhyrava.me

# Social links
#twitter_username: facespics
github_username: rnagabhyrava
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: rnagabhyrava
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rohith. I completed my graduation from Northeastern University, Boston, MA, getting a Master's degree in Data Analytics. Have a strong desire to learn and adapt to the latest technology that effectively contributes to the growth of the organization. My skillset includes
  * Programming Languages:  Python, R, Scala
  * Software & Tools:       Tableau, Microsoft Excel, Power BI, Microsoft Visio
  * Database:               Microsoft SQL Server, MySQL, MongoDB
  * Python Libraries:       TensorFlow, Keras, FastAI, Pyspark, Scikit-Learn, Numpy, Pandas, OpenCV, Plotly, Dash
  * Cloud Technologies (Intermediate): AWS (EC2, Sagemaker, S3, Elastic BeanStalk, ML APIs), GCP (Dataproc, Cloud SQL, BigQuery, Pub/Sub, ML APIs)


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
